- myuw/test/dao/card_display_dates.py
Refactored card_display_dates
Request making and processing logic is now in get_request_for_date and get_visibility_for_date.
MyPlan peak load period tests now use lists of dates to test.
> Refactored card_display_dates.py unit tests

- myuw/test/api/__init__.py
- myuw/test/api/books.py
- myuw/test/api/category_links.py
- myuw/test/api/current_schedule.py
Adds MyuwApiTest class to myuw.test.api, allowing for removal of large amounts of boilerplate code from individual test files. This handles the settings override as well.
Also provides a require_url decorator to make requiring a URL more concise and require less imports.
> Added common testing tools, starting to convert tests to use these

- myuw/test/api/__init__.py
This wasn't necessary since Django TestCase already sets up client.
> Removed unnecessary setup

- .travis.yml
This looks finds &lt;/br&gt; , which is necessary because browsers will render it as a proper &lt;br&gt;, our template precompiler will strip it out - so formatting is different on production than on local builds.
Are there other tags like that which should be disallowed?
> Adding a test for poorly formed br tags

- myuw/static/css/boilerplate.less
Fixes notices overrides so that left/right margins are removed for mobile and then re-added for 2-column layout (tablet & desktop).
> Fixes critical notice display on mobile.

- myuw/static/css/components.less
- myuw/static/css/mobile.less
- myuw/static/css/typography.less
- myuw/templates/handlebars/banner/notice.html
This adds the "sans-serif" attribute to other less files that were missed in the first pass. Also saw that Critical Notices was not properly using the new "myuw-card" style for headers and content sections - so a fix for those were added as well.
> IE11 hotfixes

- myuw/static/js/card/schedule/visual.js
takes a more defensive approach - the ifs all have an else now, so there won't be a fall through to an undefined start and end date.
> potential fix for muwm-3826

- myuw/templates/base.html
- myuw/templates/teaching/photo_list.html
Noticed that the message banner was being displayed on the class list popup. This was fixed by putting the desktop and mobile banners in template blocks in "base.html". The "photo_list.html" template then overrides them to being empty (similar to the other template blocks).
> Fixes bug that has banners displaying on class list page.

- myuw/templates/handlebars/card/hfs.html
Minor change to Husky Card card to remove "Dining" from the card title, as appropriate.
Can test with:
jinter = only has employee husky card
javerage = has all 3 husky card accounts
> adds if statement around '& Dining' to the Husky Account card title

- myuw/static/css/mobile.less
In firefox, "T" was too low and too bold.
> adjusts font weight and line height of T in vs

- myuw/static/js/ws_data.js
- myuw/test/api/instructor_schedule.py
- myuw/views/api/instructor_schedule.py
which has the side effect of getting rid of the future term instructed course card when there are zero instructed sections for that term
> client side expects 404 for non-instructed term schedules

- myuw/templates/handlebars/teaching/photo_list.html
Adds comma separator for each item in the list. Uses the "unless" conditional to check for the last item in the list and excludes the comma for that item. Single majors should always get caught by the unless they will be the only (and last?) item. 
I couldn't find where in the mock data we can add additional majors... so i'm hoping this just works.
> Adds comma separator to majors list. Fixes MUWM-3881

- myuw/templates/handlebars/card/instructor_schedule/course_cards.html
- myuw/templates/handlebars/card/instructor_schedule/course_eval.html
- myuw/templates/handlebars/card/instructor_schedule/course_grading.html
- myuw/templates/handlebars/card/instructor_schedule/course_resource/class_website.html
- myuw/templates/handlebars/card/instructor_schedule/course_resource/course_class_list.html
- myuw/templates/handlebars/card/instructor_schedule/course_resource/online_tools.html
- myuw/templates/handlebars/card/instructor_schedule/course_resource/textbooks.html
- myuw/templates/handlebars/card/instructor_schedule/course_sche_panel.html
- myuw/templates/handlebars/card/instructor_schedule/course_section.html
- myuw/templates/handlebars/card/schedule/course_resource_panel.html
- myuw/templates/handlebars/card/schedule/final_panel.html
- myuw/templates/handlebars/card/summary/schedule.html
all this does is add spaces to context variable references inside quoted href attributes. 
we need to do this to preserve quotes around hrefs in the template_preprocesss output.
the problem is with no spaces the preprocessor removes href quotes, so if after context variable substitution the href contains a space, we're screwed.
this is a little fragile going forward, so maybe we need to add a travis test to catch this.
> spaces in hrefs to preserve minified quoting

- myuw/dao/canvas.py
- myuw/test/dao/canvas.py
- myuw/views/api/instructor_schedule.py
- setup.py
independent study and courses with curricula that contained spaces were failing to match canvas course ids.
> adjusts for canvas course indep stdy

- myuw/static/css/boilerplate.less
Can test this on personal build by logging in as "bill" and viewing the Textbooks page. 
The heading "Teaching" should remain when going to mobile view, while the main page title above it becomes hidden.
> fixes MUWM-3968. only hides <h2>s of the heading class

- myuw/static/js/card/summary/schedule.js
ev.target will reference the element that was clicked on. Unfortunately, if there's a child element of the a tag, this will then pass null to the window.open call as the child element will not have a href. To avoid this, we need to change ev.target to ev.currentTarget, as currentTarget will reference the element that had the listener/event handler (the a tag in this instance).
Reference for future reference:
https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget
> Modified href source for class list link, fixing MUWM-4007

- myuw/static/css/boilerplate.less
- myuw/static/css/mobile.less
- myuw/templates/base.html
* Removes old CSS we weren't using and just overriding
* Sets a `myuw-wrapper` around the desktop message to contain its width.
> resolves MUWM-4068

- myuw/templates/handlebars/card/instructor_schedule/course_resource/course_class_list.html
- myuw/views/api/instructor_schedule.py
https://jira.cac.washington.edu/browse/MUWM-3936  
If it is a past quarter secondary section, we will display the message instead of class list links.
built on my-test, verify with kcheong3, 2017 autumn
> resolve fix/MUWM-3936

- myuw/templates/handlebars/card/teaching_resources.html
Fixing for https://jira.cac.washington.edu/browse/MUWM-4158
Updating Course Reserves link in Teaching section.
> Resolved MUWM-4158

- myuw/static/js/card/accounts/husky.js
Not using window.user.tacoma meant that the employee mailstop lookup was not being utilized. I've added an OR statement.
> Updating affiliation for Dawg Dollars display to be more incusive

- myuw/static/css/photo_list.less
Minor fix. 
- hides the icon used on class lists from the print view (saves ink!)
- adds a small bit of space between the student photo and the student's name.
> hides no photo icon on class list from print view

- Dockerfile
- docker-compose.yml
By copying in setup.py and associated files and installing them before calling the ADD command we can avoid invalidating the cache of the layers beneath it. Basically whenever the hash of files that the ADD commands adds changes, Docker realizes that it has to re-do the container layer. By installing this first we can avoid issues like this.
> Reorganizing dockerfile to minimize rebuilds

- myuw/static/css/cards.less
To test on personal build:
user: bill
class: ESS 102A spring '13
View photo class list and shrink the browser window to get the overlay to sit over the photos.
View Jira ticket for testing notes for my-test.
> resolves MUWM-4350. sets overlay z-index to 100

- myuw/static/css/mobile.less
- myuw/templates/handlebars/card/sidebar_links.html
Test on personal build with "javerage"
- View spacing of related links on Academics page. It should be the same as on the Profile, Quicklinks, Teaching page, etc.
> fixes spacing for academics page related links. resolves MUWM-3906

- myuw/static/css/photo_list.less
* Hides popup on the print view.
* Adds bottom margin to the class list so the popup can appear below the list.
Test with bill, ESS 102 A, Spring 2013. 
* Check the print view
* You'll need to narrow the browser window size to ensure the popup doesn't cover the students at the bottom.
> resolves MUWM-4364

- myuw/dao/canvas.py
- myuw/resources/canvas/file/api/v1/users/sis_user_id%3A55555333366711D5BE060004AC494FFE/enrollments_state[]_active_type[]_StudentEnrollment
- myuw/test/dao/test_canvas.py
- myuw/views/api/base_schedule.py
https://jira.cac.washington.edu/browse/MUWM-4621
This update is to handle the InvalidCanvasIndependentStudyCourse and reduce unnecessary logging of the error.
The independent_study_instructor_regid is None as the instructor of independent study section of any PRIOR quarter is NOT in SWS.  The MyUW schedule object contains the last quarter sections to display grades.  More details is in the Jira link above.
On my-test.
> Resolve MUWM-4621

- Dockerfile
The last compress use is removed from blti.
https://github.com/uw-it-aca/django-blti/commit/c12d1414c76830329f8acb4de838cb5dc64f4fd7
This is a temporary fix to make the container build without errors.
Eventually the static files need to server differently or the webpack storage file need to different
> Temporary fix to django compressor

- myuw/static/vue/components/_templates/panel.vue
- myuw/static/vue/components/academics/sidebar-links.vue
- myuw/templates/academics.html
Found this bug with Academics sidebar links. It should be displayed below the cards on mobile... and move to the sidebar on tablet/desktop.
> Adds mobileOnly logic to sidebar links (panel) for responsive UI.

- myuw/static/css/cards.less
- myuw/static/css/resources.less
This fixes the failing Develop build caused by the Less version upgrade and previous mixins call without parens. Parens have been required and are now enforced in new versions.
> Updates mixins call with parens.

- myuw/static/vue/mixins/utils.js
Instead of every component that uses nowDatetime mapping cardDisplayDates and passing that in, the mixen now maps it once.
> nowDatetime automatically tries to read the cardDisplayDates

- myuw/static/vue/components/home/quicklinks/covid-links.vue
- myuw/templates/accounts.html
fixes https://jira.cac.washington.edu/browse/MUWM-4959
Changed order so Husky card comes after HFS card in DOM; in some/most cases for students this will display it in the top-right position of the page, on a desktop.
> changing card order

- Dockerfile
- docker/app_start.sh
- docker/settings.py
- docker/urls.py
- myuw/dao/persistent_messages.py
- myuw/fixtures/persistent_messages.json
- myuw/templates/base.html
- myuw/templates/supporttools/custom_sidebar_links.html
- myuw/test/api/test_persistent_messages.py
- myuw/test/dao/test_persistent_messages.py
- myuw/test/views/test_page.py
- myuw/urls.py
- myuw/views/api/persistent_messages.py
- myuw/views/page.py
- myuw_vue/base.js
- myuw_vue/components/_templates/boilerplate/banner_message.vue
- myuw_vue/components/_templates/boilerplate/messages.vue
- myuw_vue/tests/banner_message.test.js
- setup.py
MUWM-4885: 
* Add persistent_message on support page,
* Add the banner_message vue component
* styling persistent messages banner and onboarding banner.
Co-authored-by: Charlon Palacay <charlon@gmail.com>
Co-authored-by: William Washington <williamwashington@Williams-MacBook-Pro.local>
> Add persistent_message on support page (#2749)

- Dockerfile
- docker/dev-values.yml
- docker/prod-values.yml
- docker/test-values.yml
- docker/vue-values.yml
- myuw/management/commands/db_cleanup.py
[MUWM-5196](https://jira.cac.washington.edu/browse/MUWM-5196): switch over to postgres DB
> Resolve MUWM-5196: switch over to postgres DB (#3034)

- .github/workflows/cicd.yml
- docker/prod-values.yml
- docker/test_python.sh
- myuw/resources/pws/file/identity/v2/person.json_student_number_1033334_verbose_on
- myuw/templates/restclients/customform/sws/student.html
- myuw/test/views/test_rest_search.py
- myuw/views/rest_search.py
- myuw_vue/components/home/new_student/to-register.vue
- package.json
https://jira.cac.washington.edu/browse/MUWM-5355
> revising static notices messaging & styles

- myuw/test/util/test_cache.py
- myuw/util/cache.py
- myuw/views/rest_search.py
- myuw_vue/components/home/summaries.vue
- myuw_vue/tests/summaries.test.js
https://jira.cac.washington.edu/browse/MUWM-5364
> Resolve MUWM-5364
