myuw_mobile/static/js/banner/profile.js, myuw_mobile/static/js/myuw_m.js, myuw_mobile/templates/base_mobile.html, myuw_mobile/templates/handlebars/banner/profile.html
=> Adding loading spinner to profile

myuw_mobile/data/category_links_import.csv, myuw_mobile/templates/handlebars/card/academic.html
=> updating links to DARS

myuw/management/commands/linkcheck.py
Revised link checker that uses the dao interface to find all resource links.
=> Revised link checker

myuw/test/api/academic_calendar.py, myuw/test/api/cur_books.py, myuw/test/api/finance.py, myuw/test/api/future_schedule.py, myuw/test/api/grad.py, myuw/test/api/hfs.py
Refactors academic_calendar, cur_books, finance, future_schedule, and hfs.
=> Next round of refactors

myuw/test/api/__init__.py, myuw/test/api/iasystem.py, myuw/test/api/library.py, myuw/test/api/myplan.py, myuw/test/api/notices.py, myuw/test/api/other_quarters.py, myuw/test/api/profile.py, myuw/test/api/thrive.py, myuw/test/api/uwemail.py
Last round of refactoring for API tests
=> Another round of refactoring

myuw/test/dao/calendar.py, myuw/test/dao/course_color.py, myuw/test/dao/library.py, myuw/test/dao/notice.py, myuw/test/dao/term.py, myuw/test/views/mobile_login.py, myuw/tests.py
Fixes test names to not overlap so they all get run.
Refactors test.views.mobile_login
=> More unit test fixes

.travis.yml, myuw/test/api/__init__.py
And then it sets that for travis-ci
=> Adds an option to force run the view tests

myuw/data/forward_mapping.csv, myuw/templates/base.html
resolves https://trello.com/c/1lpLi8Hx (minor updates: removes li element when no email; updates icon and link text on csv)
resolves https://trello.com/c/UVE1t1ci  (underline bug)
=> minor updates to mapping csv; resolves bugs on base.html

myuw/views/api/base_schedule.py, myuw/views/api/category_links.py, myuw/views/api/current_schedule.py, myuw/views/api/finance.py, myuw/views/api/future_schedule.py, myuw/views/api/grad.py, myuw/views/api/hfs.py, myuw/views/api/iasystem.py, myuw/views/api/instructor_schedule.py, myuw/views/api/library.py, myuw/views/api/myplan.py, myuw/views/api/notices.py, myuw/views/api/other_quarters.py, myuw/views/api/profile.py, myuw/views/api/textbook.py, myuw/views/api/thrive.py, myuw/views/error.py, myuw/views/page.py, myuw/views/rest_dispatch.py
These errors were used by views outside of rest dispatching, and I think it makes sense to have a module that covers the error cases.  Also added a few http and myuw http status code constants.
=> Moving view errors to a new module

myuw/templates/supporttools/custom_sidebar_links.html
Are there more things that should be added now?
=> Adding a link to the restclients errors page

myuw/test/api/profile.py, myuw/views/__init__.py, myuw/views/api/profile.py
Remove the logic that would hide the password content.
=> Enable password

myuw/static/css/mobile.less, myuw/templates/base.html, myuw/templates/search_res.html
Note: This has my Google Custom Search dev account linked to it.
=> styling google search results and paginator controls

myuw/static/css/mobile.less, myuw/templates/handlebars/card/schedule/course_card_content.html, myuw/templates/handlebars/card/schedule/course_cards.html
=> Hlee2 closed section

myuw/static/css/mobile.less, myuw/templates/handlebars/card/accounts/account_card.html
Mostly reorganizing the HTML of the staff card. styles the workday link.
=> adjustments to Staff card HTML

myuw/static/css/mobile.less, myuw/templates/handlebars/card/directory_info.html
@mikeseibel Adding a lot of placeholder markup for you to use.
=> adding markup for new directory data

myuw/templates/handlebars/card/directory_info.html
=> adding more semantic RDFa markup to directory_info card

myuw/static/css/mobile.less, myuw/templates/handlebars/card/directory_info.html
wraps profile data in 'if' statements. prints 'no data available' messages otherwise.
=> adds conditionals around data

myuw/static/js/textbooks.js
This should fix the issue with the future quarter textbooks not displaying properly
=> Fixed bug with future quarter textbooks

myuw/templates/admin/messages.html
This is a minor bugfix to resolve a width issue. klpittman feel free to expand the scope of review if you have other thoughts about admin tool ui.
=> banner messages admin page update

myuw/dao/term.py, myuw/static/js/card/summary/accounts.js, myuw/templates/handlebars/card/summary/accounts.html, myuw/templates/index.html, myuw/test/dao/test_term.py
Also improves winter break's display
=> Makes the term data used to show the term break a distinct field.

myuw/templates/handlebars/card/student_info.html
fixes typo and  update the text
=> Fixes MUWM-3813

myuw/templates/handlebars/card/profile/profile_card.html
Adding data-link for Quick Links
=> Fixes MUWM-3814

myuw/templates/handlebars/card/student_info.html
Removed the second 'Change address' link
=> Fixes MUWM-3818

myuw/templates/handlebars/card/profile/profile_card.html
=> Fixes MUWM-3824

myuw/static/css/dropmenus.less, myuw/static/css/tabs.less
Minor change to deal with mobile size for tabs on the Teaching page.
=> makes adjustments to page tabs/menu for mobile size

myuw/dao/messages.py, myuw/test/dao/test_banner_message.py, myuw/test/speed.py
@wmwash i think this gives you the styling control you need.  if not, can you request changes on here w/ anything more?
=> Allowing classes for font-awesome, and a small set of styles

myuw/templates/base.html
test visually with students: javerage, eight, jnew and jpce and non-students bill, billtac
=> shows notices link for students only

myuw/static/css/components.less, myuw/static/js/test/directory_info.js, myuw/templates/handlebars/card/directory_info.html, myuw/templates/workday_link.html
This styles the employee profile in the same 2-column layout as student profiles.
=> Updates employee profile to new 2 column card layout.

myuw/static/css/course_card.less, myuw/templates/handlebars/card/instructor_schedule/course_grading.html, myuw/templates/handlebars/card/instructor_schedule/course_resource/class_website.html, myuw/templates/handlebars/card/schedule/final_day.html, myuw/templates/handlebars/card/schedule/visual_day.html
1. square instead of circle for teaching T on visual schedule 
2. warning icon to error message of course website 
3. lighter color for question mark help icon on instructor course details
=> visual design enhancements, part deux

myuw/templates/handlebars/card/instructor_schedule/course_sche_panel.html, myuw/templates/handlebars/card/schedule/course_sche_col_bldg.html
=> fixes final exam location link text. Adds title attribute.

myuw/static/js/card/instructor_schedule/load_section_card.js, myuw/static/js/card/schedule/visual.js, myuw/static/js/card/summary/schedule.js
on InstructorSectionCard, VisualScheduleCard, SummaryScheduleCard
resolve MUWM-3859
Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
at Object.<anonymous> (f12c6bb20aed.js:109)
at Function.each (jquery-1.11.0.min.js:2)
at Object.normalized_instructed_course_data (f12c6bb20aed.js:105)
at Object._has_all_responses (f12c6bb20aed.js:525)
at render_handler (f12c6bb20aed.js:525)
at Object._run_success_callbacks_for_url (f12c6bb20aed.js:96)
at Object.success (f12c6bb20aed.js:131)
at j (jquery-1.11.0.min.js:2)
at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js:2)
at x (jquery-1.11.0.min.js:4) 
Verified on my-test-app01
=> replace hasOwnProperty

myuw/templates/handlebars/card/instructor_schedule/course_cards.html, myuw/templates/handlebars/card/instructor_schedule/course_section.html
=> section_references doesn't have index build-in. user @index.

myuw/static/js/card/instructor_schedule/load_section_card.js, myuw/static/js/card/summary/future_schedule.js, myuw/static/js/card/summary/schedule.js, myuw/templates/handlebars/card/summary/schedule.html
Personal build
user: bill100
date: 2013-01-15 00:00:01
=> Fix future quarter 10+ course issue

myuw/templates/handlebars/card/instructor_schedule/course_resource/online_tools.html, myuw/templates/handlebars/card/instructor_schedule/course_resource_panel.html
Can test with:
TRAIN 100 A (Spring '13)
"bill"
=> moves <li> to online_tools.html. fixes muwm-3900.

myuw/static/js/card/instructor_schedule/course_resource_panel.js, setup.py
https://jira.cac.washington.edu/browse/MUWM-3924
=> resolve MUWM-3924

myuw/static/css/mobile.less, myuw/templates/handlebars/card/summary/schedule.html
Fixes 3929. just sticks to the location we are currently using.
=> adds right margin to future quarter preview

myuw/static/css/mobile.less, myuw/templates/handlebars/card/summary/schedule.html
Use billpce to see the problem fixed with the original CLS class type.
=> adds classes, responsive definitions. Fixes MUWM-3940

myuw/static/js/card/summary/schedule.js, myuw/templates/handlebars/card/summary/schedule.html
https://jira.cac.washington.edu/browse/MUWM-3956
=> Resolve MUWM-3956

myuw/static/js/card/summary/future_schedule.js
=> Fix the first day of class on future term summary card.

myuw/static/js/card/outage.js, myuw/static/js/card/profile/profile.js, myuw/static/js/test/outage_card.js
https://jira.cac.washington.edu/browse/MUWM-3960
=> Resolve MUWM-3960

myuw/templates/handlebars/card/schedule/visual.html
can be viewed on branch (in Au quarter preview page) with
user: javerage
date: 2013-06-26 00:00:01
=> adding Autumn 2017 start date to VS.

myuw/static/js/card/instructor_schedule/course_card_content.js, myuw/static/js/card/instructor_schedule/course_resource_panel.js, myuw/static/js/card/summary/schedule.js
Applied Ethan's fix in all the applicable places.
=> Resolve MUWM-4007

myuw/templates/handlebars/card/outage.html
https://jira.cac.washington.edu/browse/MUWM-3987
=> resolve MUWM-3987

myuw/static/css/components.less, myuw/templates/handlebars/card/quicklinks.html
Adds a z-index to the popover form. Moves it to a css class.
=> fixes muwm-4010

myuw/dao/instructor_schedule.py, myuw/templates/handlebars/card/instructor_schedule/course_sche_panel.html, myuw/test/api/instructor_schedule.py, myuw/test/dao/instructor_schedule.py, myuw/views/api/instructor_schedule.py
https://jira.cac.washington.edu/browse/MUWM-4001
=> Resolve MUWM-4001

myuw/templates/handlebars/card/schedule/visual.html
https://jira.cac.washington.edu/browse/MUWM-3965
Removes the start on date text.
Test as "javerage"
=> resolves MUWM-3965

myuw/templates/handlebars/card/seattle_application.html
Remove a part of the contact info and add a registration info.
=> Update the text

myuw/static/css/mobile.less, myuw/templates/base.html
Removes some unused CSS in the footer as well.
=> resolves muwm-4040

myuw/templates/handlebars/card/seattle_application.html
UI text tweak for the Seattle returning application card
=> tweak the returning app card text

myuw/static/css/boilerplate.less, myuw/templates/base.html
@charlon Had to move some of the welcome message to inside the navigation block so it wouldn't show up on the class list popup page. Had to move some of the margin too because of that. Take a look if you have time.
=> resolves bug MUWM-4045.

myuw/static/css/components.less, myuw/templates/base.html
Changes implementation for hiding footer links at desktop size. Creates a myuw specific class similar to bootstraps hide/show helper utility classes.
=> resolves MUWM-4077

myuw/templates/handlebars/card/schedule/visual.html
Take 2: adding the Winter quarter date
=> adding the Winter qtr start date

myuw/static/css/mobile.less
change period tab underline color
=> MUWM-4110 change period tab underline color

myuw/views/link.py
If I understand Patrick's intention correctly,  is_anonymous should be is overriding
=> Resolve muwm-4124

myuw/dao/user.py, myuw/data/opt_in_list.txt, myuw/test/dao/__init__.py, myuw/test/dao/user.py
On your personal build, you may remove jeos from your local data/opt-in-list file and test.
On my-test, use what mentioned in Comment of https://jira.cac.washington.edu/browse/MUWM-4129
=> Resolve MUWM-4129

myuw/static/js/test/events.js, myuw/templates/handlebars/card/calendars/events.html
https://jira.cac.washington.edu/browse/MUWM-4154
test: javerage
=> resolve MUWM-4154

myuw/templates/handlebars/card/accounts/library.html
https://jira.cac.washington.edu/browse/MUWM-4153
=> Resolve MUWM-4153

myuw/dao/instructor_schedule.py, myuw/resources/sws/file/student/v5/course/2018_spring_JAPAN_573/A.json, myuw/resources/sws/file/student/v5/section.json_reg_id_10000000000000000000000000000006_search_by_Instructor_quarter_spring_include_secondaries__year_2018_future_terms_2_transcriptable_course_all, myuw/resources/sws/file/student/v5/section.json_reg_id_10000000000000000000000000000006_search_by_Instructor_quarter_spring_include_secondaries_on_year_2018_future_terms_0_transcriptable_course_all, myuw/test/dao/instructor_schedule.py
https://jira.cac.washington.edu/browse/MUWM-3971
Unit tests coverage: https://coveralls.io/builds/15620674/source?filename=myuw%2Fdao%2Finstructor_schedule.py
Test spec: https://docs.google.com/document/d/1nrz3_gW0c9UQKj_TUOMT-_U6UV8Y-HauurWEGh4TuGE/edit
=> Resolve MUWM-3971

myuw/data/forward_mapping.csv, myuw/resources/uwnetid/file/nws/v1/uwnetid/retirestaff/subscription/60,64,105, myuw/test/dao/emaillink.py
https://jira.cac.washington.edu/browse/MUWM-4165
Built on my-test.
Personal build: retirestaff
My-test: cmaranto
=> resolve MUWM-4165

myuw/static/js/ws_data.js, myuw/templates/handlebars/card/instructor_schedule/course_resource/class_website.html
This is currently built on my-dev, override netid in the jira ticket.
=> Fixing MUWM-4006

myuw/templates/handlebars/card/instructor_schedule/course_cards.html
https://jira.cac.washington.edu/browse/MUWM-4193
=> resolves MUWM-4193

myuw/templates/handlebars/card/schedule/course_cards.html
=> resolves MUWM-3857

myuw/static/css/mobile.less, myuw/templates/handlebars/card/schedule/eval_panel.html
See bug for testing notes: https://jira.cac.washington.edu/browse/MUWM-3784
=> resolves MUWM-3784

myuw/dao/gws.py, myuw/dao/user.py, myuw/resources/gws/file/group_sws/v2/search_member_botgrad_scope_all_type_effective_stem_uw_affiliation, myuw/resources/gws/file/group_sws/v2/search_member_curgrad_scope_all_type_effective_stem_uw_affiliation, myuw/resources/gws/file/group_sws/v2/search_member_jerror_scope_all_type_effective_stem_uw_affiliation, myuw/resources/gws/file/group_sws/v2/search_member_seagrad_scope_all_type_effective_stem_uw_affiliation, myuw/resources/gws/file/group_sws/v2/search_member_tacgrad_scope_all_type_effective_stem_uw_affiliation, myuw/test/dao/test_gws.py, myuw/test/dao/user.py
https://jira.cac.washington.edu/browse/MUWM-4198
=> Resolve MUWM-4198

myuw/templates/handlebars/card/bothell_application.html
Use _japplicant_ on branch to see fix on Bothell Application card.
=> fixing typo in email address.

myuw/templates/base.html
A minor fix of the onboarding modal image and a link update
=> Fix image for tiny viewport and update a link

myuw/resources/sws/file/student/v5/registration.json_curriculum_abbreviation_ESS_instructor_reg_id__course_number_102_verbose_true_year_2013_quarter_spring_is_active_true_section_id_A_transcriptable_course_all, myuw/test/api/test_instructor_section.py, myuw/views/api/instructor_section.py
=> Adding fix for MUWM-4186

myuw/static/css/boilerplate.less, myuw/static/css/desktop.less, myuw/static/css/mobile.less, myuw/templates/handlebars/banner/notice.html
* Some HTML and CSS cleanup. 
* hide/show the other notices
@devights can you double check that the regular notice list is pulling the right notices? For javerage I was seeing duplicate notices in both lists. Maybe just a mock data issue but want to double check.
=> styles other notices. Makes them collapsable.

myuw/static/js/ws_data.js
Built on my-test and tested on the AXDD Windows computer.
=> Changing object.assign to $.extend

myuw/templates/handlebars/card/schedule/final_panel.html
Shorten the Su final exam message.
=> Update the final exam message

myuw/static/css/mobile.less, myuw/static/js/card/schedule/visual.js
Visual schedule 6 day schedule border and extra space at right were fixed. 
MUWM-4056: 6 day visual schedule bottom border is missing
MUWM-3820: Visual schedule border for 6 day table inconsistent
MUWM-4223: weird VS layouts
=> fixing VS border and extra space

myuw/templates/handlebars/card/profile/student_info.html
https://jira.cac.washington.edu/browse/MUWM-2128
personal branch testing:
javerage
Local address line 1: 4634 26th Ave NE
Local address line 2: APT 102
Permanent address line 1: 1645 140th Ave NE
Permanent address line 1: APT 980
=> resolves MUWM-2128

Dockerfile, docker/settings.py, docker/urls.py, docker/wsgi.py, travis-ci/settings.py
The Docker build system requires that the travis-ci/settings.py file be kept up to date with required settings as it uses it as a template.
=> Adding settings to travis-ci

myuw/data/quicklinks.csv
Updated "Time Schedule - Bothell" to "https://www.uwb.edu/registration/time"
=> Resolved MUWM-4252

myuw/dao/__init__.py
https://jira.cac.washington.edu/browse/MUWM-4270
=> Resolve MUWM-4270

myuw/templates/handlebars/card/calendars/academic_calendar.html
Removes the `<center>` element wrapper. 
Adds the "center-block" class to the existing `<div>` element wrapping the button group.
=> resolves MUWM-3844

myuw/templates/handlebars/card/teaching_resources.html
Can test with "bill". 
New link is added to Web Tools & Services on the Teaching page.
=> resolves MUWM-4003. adds link to Teaching resources

myuw/templates/supporttools/custom_sidebar_links.html
=> add comment

myuw/static/css/mobile.less, myuw/templates/handlebars/card/registration/myplan_courses.html
tested with `jinter`
default mock date of 2013-04-15 00:00:01
Not sure how to get it to show up with more than one meeting time, nor the "dates to be determined" message...
=> resolves MUWM-3625

myuw/dao/user_course_display.py, myuw/static/js/card/future_quarter.js, myuw/test/dao/test_user_course_display.py
https://jira.cac.washington.edu/browse/MUWM-4292
Couldn't find a way to unit-test the IntegrityError. Suggestion will be appreciated.
=> Resolve MUWM-4292

Dockerfile, docker-compose.yml, docker/settings.py, docker/web/httpd.conf, docker/web/start.sh, docker/wsgi.py
Our app servers will now have a single Apache host and a MySQL DB host. Next I'll work on adding a memcached server, then a CDN and a load balancer so we'll have full parity with production.
=> Setting up Apache

myuw/templates/handlebars/card/accounts/upass.html
Test on personal branch: "botgrad"
=> fixes broken u-pass link for Bothell Campus

myuw/templates/500.html, myuw/templates/handlebars/card/no_course.html, myuw/templates/handlebars/error.html, myuw/templates/handlebars/panel/no_courses.html
https://jira.cac.washington.edu/browse/MUWM-4304
Testing notes:
- jinter, view the academics page to see the no_courses card
- not sure how to view myuw/templates/handlebars/panel/no_courses.html
- View the 500 page at /500
- Not sure how to view myuw/templates/handlebars/error.html
=> updates old links to legacy contact form

myuw/static/js/handlebars-helpers.js
=> Try to fix encodeForMaps not found error.

myuw/templates/handlebars/card/schedule/course_resource_panel.html
Testing: javerage
Academics cards
=> resolves MUWM-4321. Comments out unfinished error message work

myuw/data/quicklinks.csv
tested with:
* jalum (test to see if Email Forwarding still shown)
* retirestaff (test to see if Email Forwarding still shown)
* javerage (test to see if Email Forwarding link no longer shown)
=> updates quicklinks. resolves MUWM-4326

myuw/templates/handlebars/card/seattle_application.html
Steps to verify:
1. Override as japplicant
2. In the JS console enter the following two commands (pressing enter after each)
`WSData._applicant_data[1].is_returning = true;`
`SeattleApplicationCard._render();`
=> swapping fee msg for confirm msg

myuw/dao/registration.py, myuw/test/dao/test_registration.py, myuw/views/api/base_schedule.py
https://jira.cac.washington.edu/browse/MUWM-4360  (ignore TS Print when getting registration record)
Built on my-dev, testid: ecarll
Personal build: javerage, 2014 winter quarter PHYS, 122, A
=> Resolve MUWM-4360

setup.py
=> Upgrading django

myuw/dao/calendar.py, myuw/test/api/academic_calendar.py, myuw/views/api/academic_events.py
https://jira.cac.washington.edu/browse/MUWM-4485
Built on my-test
=> Resolve MUWM_4485

myuw/static/css/mobile.less
See bug for testing/production details: https://jira.cac.washington.edu/browse/MUWM-4497
=> font and color change for improved search readability.

myuw/dao/canvas.py, myuw/resources/canvas/file/api/v1/users/sis_user_id%3A12345678901234567890123456789012/enrollments_state[]_active_type[]_StudentEnrollment, myuw/test/dao/test_canvas.py
See https://jira.cac.washington.edu/browse/MUWM-4617 for details.
Built on my-test
=> Resolve fix/MUWM-4617

myuw/management/commands/clear_expired_sessions.py, myuw/test/management/commands/test_clear_expired_sessions.py
https://jira.cac.washington.edu/browse/MUWM-4482
The cron job will run daily at 7pm. Will finish by 7am.
=> Resolve MUWM-4482

myuw/dao/__init__.py, myuw/dao/gws.py, myuw/test/api/test_banner_message.py, myuw/test/dao/__init__.py, myuw/test/dao/test_gws.py, myuw/test/util/test_settings.py, myuw/test/views/test_errors.py, myuw/test/views/test_page.py, myuw/tests.py, myuw/util/settings.py, myuw/views/error.py, myuw/views/page.py
https://jira.cac.washington.edu/browse/MUWM-4234
On my-dev
=> Resolve fix/MUWM-4234

myuw/dao/uwnetid.py, myuw/static/js/landing.js, myuw/static/js/test/page_home.js
https://jira.cac.washington.edu/browse/MUWM-4476
Built on my-test
=> Resolve MUWM-4476

Dockerfile
May not need to be merged if we want to keep it out of the Dockerfile, see:
https://github.com/less/less.js/issues/3469
=> Docker builds are failing, unable to find tslib.

myuw/models/__init__.py, myuw/test/model/test_link.py
https://jira.cac.washington.edu/browse/MUWM-4587
=> Resolve MUWM-4587

myuw/test/api/emaillist.py, myuw/test/api/test_banner_message.py, myuw/test/api/test_instructor_section_display.py, myuw/test/api/test_quicklinks.py, myuw/test/api/test_resources.py, myuw/test/views/lti/test_photo_list.py, myuw/test/views/test_display_dates.py, myuw/test/views/test_errors.py, myuw/test/views/test_link_admin.py, myuw/test/views/test_page.py, myuw/views/api/affiliation.py, myuw/views/decorators.py, myuw/views/error.py
https://jira.cac.washington.edu/browse/MUWM-4680
=> Resolve MUWM-4680

myuw/test/dao/test_pws.py, myuw/test/views/test_page.py
https://jira.cac.washington.edu/browse/MUWM-4366
=> Verify MUWM-4366

myuw/dao/applications.py, myuw/test/api/test_applications.py
https://jira.cac.washington.edu/browse/MUWM-4361
=> Resolve fix/MUWM-4361

myuw/dao/card_display_dates.py, myuw/test/dao/card_display_dates.py
https://jira.cac.washington.edu/browse/MUWM-3430
=> Resolve MUWM-3430

myuw/views/link.py, myuw/views/page.py
https://jira.cac.washington.edu/browse/MUWM-4699
=> Resolve MUWM-4699

myuw/templates/500.html
https://jira.cac.washington.edu/browse/MUWM-4702?jql=project%20%3D%20MUWM%20AND%20fixVersion%20%3D%207.17.1
=> Resolve MUWM-4702

myuw/templates/500.html
=> Resolve MUWM-4703

myuw/test/views/test_link.py, myuw/views/link.py
https://jira.cac.washington.edu/browse/MUWM-4704
=> Resolve MUWM-4704

docker/settings.py, myuw/test/views/test_page.py, myuw/views/page.py
Details see
https://jira.cac.washington.edu/browse/MUWM-4710
=> Resolve MUWM-4710

myuw/views/page.py
https://jira.cac.washington.edu/browse/MUWM-4719
=> Resolve MUWM-4719

.travis.yml, myuw/data/resource_link_import.csv, myuw/templates/handlebars/card/instructor_schedule/course_resource_panel.html, myuw/templates/handlebars/card/teaching_resources.html, myuw/test/api/test_resources.py, myuw/test/dao/test_category_links.py, myuw/tests.py
https://jira.cac.washington.edu/browse/MUWM-4720
Verify on dev.my.uw.edu
=> Resolve MUWM-4720

docker-compose.yml, docker/settings.py
django-compressor wasn't hot reloading any static files
=> compile offline is now set with a env variable

Dockerfile, docker/prod-values.yml
https://jira.cac.washington.edu/browse/MUWM-4739
=> Resolve MUWM-4739

myuw/data/category_links_import.csv, myuw/data/resource_link_import.csv, myuw/test/dao/test_category_links.py
https://jira.cac.washington.edu/browse/MUWM-4759
=> Resolve MUWM-4759

myuw/data/resource_link_import.csv
=> update hall health url

myuw/resources/sws/file/student/v5/course/2013_spring_BIGDATA_230/A.json, myuw/test/dao/test_visual_schedule.py, myuw/tests.py
https://jira.cac.washington.edu/browse/MUWM-4800
=> Resolve MUWM-4800

myuw/static/vue/components/index/cards/quicklinks/link.vue
Fixes list item alignment extra space. Now matches Notices list for conistency.
=> Fixes list item alignment extra spacing.

.travis.yml, docker/test-values.yml, myuw/resources/sws/file/student/v5/registration.json_reg_id_55555333366711D5BE060004AC494FFE_transcriptable_course_all_quarter_summer_is_active_true_year_2013_verbose_on, myuw/test/dao/test_visual_schedule.py, setup.py
https://jira.cac.washington.edu/browse/MUWM-4808
=> resolve MUWM-4808

myuw/static/vue/base.js, myuw/static/vue/components/cards/schedule/course-section.vue, myuw/static/vue/components/cards/schedule/visual-schedule.vue, myuw/static/vue/components/index/cards/applicant/bothell.vue, myuw/static/vue/components/index/cards/applicant/seattle.vue, myuw/static/vue/components/index/cards/applicant/tacoma.vue, myuw/static/vue/components/index/summaries.vue, myuw/static/vue/mixin/outlink.js, myuw/static/vue/mixin/utils.js, myuw/static/vue/tests/applicant.test.js, myuw/static/vue/tests/critical-info.test.js, myuw/static/vue/tests/events.test.js, myuw/static/vue/tests/grades.test.js, myuw/static/vue/tests/helper.js, myuw/static/vue/tests/inter_stud.test.js, myuw/static/vue/tests/notices.test.js, myuw/static/vue/tests/outage.test.js, myuw/static/vue/tests/quicklinks.test.js, myuw/static/vue/tests/summaries.test.js, myuw/static/vue/tests/utils.test.js, myuw/static/vue/tests/visual-schedule.test.js
Resolves https://jira.cac.washington.edu/browse/MUWM-4803.
=> Moves common functions into mixins and add a mixin to handle outbound links

myuw/static/vue/components/cards/husky-experience.vue, myuw/static/vue/components/index/summaries.vue, myuw/static/vue/containers/card.vue
Minor fix to account summaries positioning outside of main container. Updates card.vue global tabindex.
=> Remove card tabindex and fixes summaries positioning.

myuw/resources/myplan/file/student/api/plan/v1/2013_summer_1_12345678901234567890123456789012, myuw/test/api/test_myplan.py, myuw/tests.py
https://jira.cac.washington.edu/browse/MUWM-4835
=> fix mock data

myuw/templates/handlebars/card/grad_status.html
https://jira.cac.washington.edu/browse/MUWM-4809
=> Resolve MUWM-4809

.travis.yml, myuw/static/js/card/calendars/events.js, myuw/templates/handlebars/card/calendars/events.html
https://jira.cac.washington.edu/browse/MUWM-4834
Built on dev.my.edu
=> display Zoom at event location field

myuw/test/api/test_current_schedule.py, myuw/views/api/base_schedule.py
https://jira.cac.washington.edu/browse/MUWM-4863
=> Resolve MUWM-4863

myuw/static/vue/components/textbooks/covid.vue, myuw/static/vue/components/textbooks/textbooks.vue
I fixed the bookstore covid message yellow color. Addressed the contrast color you brought up.
=> Fixes Bookstore covid message styles.

.travis.yml, myuw/models/__init__.py, myuw/test/api/test_banner_message.py, myuw/test/dao/test_user.py, setup.py
https://jira.cac.washington.edu/browse/MUWM-4876
=> Up django version to 2.1.15

myuw/templates/handlebars/teaching/photo_list.html
Made edits to text wrapping in the pronouns column in class list
=> Edited text wrapping in pronouns in class list

myuw/views/error.py
https://jira.cac.washington.edu/browse/MUWM-4895
=> Resolve MUWM-4895

myuw/views/page.py
https://jira.cac.washington.edu/browse/MUWM-4700
=> Resolve MUWM-4700

myuw/static/vue/vuex/store/common.js, myuw/static/vue/vuex/store/notices.js, myuw/static/vue/vuex/store/schedule/common.js, myuw/static/vue/vuex/store/schedule/instructor.js, myuw/static/vue/vuex/store/schedule/visual.js
=> Moved all the plugin extensions (from vuex/store) into one file

myuw/static/vue/components/husky_experience/husky-exp.vue
=> Husky Experience Fix

myuw/static/vue/academics.js, myuw/static/vue/accounts.js, myuw/static/vue/base.js, myuw/static/vue/calendar.js, myuw/static/vue/components/_common/uw-netid.vue, myuw/static/vue/components/_templates/boilerplate/boilerplate.vue, myuw/static/vue/components/academics/grad-committee.vue, myuw/static/vue/components/academics/grad-status.vue, myuw/static/vue/components/accounts/hfs-sea.vue, myuw/static/vue/components/accounts/husky.vue, myuw/static/vue/components/accounts/tuition-fees.vue, myuw/static/vue/components/home/inst_course_summary/summary.vue, myuw/static/vue/future_quarters.js, myuw/static/vue/home.js, myuw/static/vue/husky_experience.js, myuw/static/vue/mixins/utils.js, myuw/static/vue/notices.js, myuw/static/vue/profile.js, myuw/static/vue/resources.js, myuw/static/vue/teaching.js, myuw/static/vue/teaching_classlist.js, myuw/static/vue/tests/mixins.test.js, myuw/static/vue/textbooks.js
1. Lined up navigation icons by adding 'fixed-width' to icons.
2. Made error messages within cards more consistent by leaving out 'page' or 'portal' from the links.
3. Made the MyUW title clickable so that it directs to Home page.
4. Made the 'pageTitle' string into the 'page' object that contains two elements: title and hideTitle.
TODO: Remove the underlined whitespace in the netid, email, and search links at the top of the boilerplate.
=> various bug fixes

myuw/data/category_links_import.csv, myuw/data/resource_link_import.csv, myuw/static/vue/components/home/quicklinks/covid-links.vue, myuw/static/vue/components/teaching/teaching-resources.vue
https://jira.cac.washington.edu/browse/MUWM-4946
=> Resolve MUWM-4946

myuw/static/vue/components/teaching/course/grading.vue
https://jira.cac.washington.edu/browse/MUWM-4954
=> Resolve MUWM-4954

myuw/static/vue/components/teaching/course/materials/email-modals/request.vue
https://jira.cac.washington.edu/browse/MUWM-4961
=> Fix for MUWM-4961

myuw/dao/visual_schedule.py, myuw/resources/sws/file/student/v5/registration.json_reg_id_FBB38FE46A7C11D5A4AE0004AC494FFE_transcriptable_course_all_quarter_summer_is_active_true_year_2013_verbose_on, myuw/test/dao/test_visual_schedule.py
https://jira.cac.washington.edu/browse/MUWM-4973
=> Resolve MUWM-4973

myuw/static/vue/tests/mock_data/notice/grad-c2.json, myuw/static/vue/tests/mock_data/tuition/grad-c2.json, myuw/static/vue/tests/mock_data/tuition/javerage.json, myuw/static/vue/tests/mock_data/tuition/jbothell.json, myuw/static/vue/tests/tuition.test.js, myuw/static/vue/vuex/store/tuition.js
https://jira.cac.washington.edu/browse/MUWM-4978
=> Add test and mock data for the bug case

myuw/static/vue/base.js, myuw/static/vue/components/_templates/card-table.vue, myuw/static/vue/components/teaching/classlist/table-view.vue, myuw/static/vue/mixins/sort-compare.js, myuw/static/vue/tests/classlist-table-view.test.js, myuw/static/vue/tests/helper.js, myuw/static/vue/tests/mixins.test.js, myuw/static/vue/tests/store/classlist.test.js
convert b-table to table, add jest tests
=> Vue/rp b table (#2527)

myuw/static/vue/components/_common/term-selector.vue, myuw/static/vue/components/_common/visual_schedule/schedule.vue, myuw/static/vue/components/_templates/tabs/tab.vue, myuw/static/vue/components/_templates/tabs/tabs.vue, myuw/static/vue/components/home/international/student.vue, myuw/static/vue/components/teaching/classlist/content.vue
Here is my tab styling implementation.
=> Styling tabs.

myuw/resources/sws/file/student/v5/notice/9136CCB8F66711D5BE060004AC494FFE.json, myuw/resources/sws/file/student/v5/notice/FE36CCB8F66711D5BE060004AC494FCD.json, myuw/static/vue/components/_common/visual_schedule/schedule.vue, myuw/static/vue/components/_templates/boilerplate/boilerplate.vue, myuw/static/vue/components/home/new_student/to-register.vue, myuw/static/vue/tests/to-register.test.js
https://jira.cac.washington.edu/browse/MUWM-4988
The qa branch will be merged back into develop after this PR
=> Resolve MUWM-4988

docker/settings.py
https://jira.cac.washington.edu/browse/MUWM-4990
Hole the merge
=> Resolve MUWM-4990

myuw/static/vue/components/_templates/boilerplate/boilerplate.vue, myuw/static/vue/components/_templates/card-property-group.vue, myuw/static/vue/components/academics/adviser.vue, myuw/static/vue/components/home/inst_course_summary/section.vue, myuw/static/vue/components/home/new_student/to-register.vue, myuw/static/vue/components/home/quicklinks/covid-links.vue, myuw/static/vue/components/home/quicklinks/quicklinks.vue, myuw/static/vue/components/home/resources/resource-explore.vue, myuw/static/vue/components/resources/resources.vue, myuw/static/vue/components/textbooks/covid.vue, myuw/static/vue/components/textbooks/section.vue, myuw/static/vue/components/textbooks/textbooks.vue, myuw/templates/admin/popular_links.html
Light hr color. Not exact, but uses a default theme color.
=> Sets lighter hr color from BS5 update.

myuw/static/vue/components/teaching/course/final-exam.vue, myuw/static/vue/components/teaching/course/grading.vue, myuw/static/vue/components/teaching/course/materials/website.vue
https://jira.cac.washington.edu/browse/MUWM-4999
=> Resolve MUWM-4999

myuw/static/vue/components/_templates/boilerplate/boilerplate.vue, myuw/static/vue/husky_experience.js, setup.py
https://jira.cac.washington.edu/browse/MUWM-5006
=> Resolve MUWM-5006

myuw/static/vue/components/_common/grades.vue, myuw/static/vue/components/_common/visual_schedule/schedule.vue, myuw/static/vue/components/home/registration/status.vue, myuw/static/vue/tests/grades.test.js, myuw/static/vue/tests/reg_status.test.js, myuw/static/vue/tests/visual-schedule.test.js
https://jira.cac.washington.edu/browse/MUWM-5016
=> Resolve MUWM-5016

docker/dev-values.yml, docker/prod-values.yml, docker/settings.py, docker/test-values.yml, docker/vue-values.yml, myuw/templates/restclients/customform/attest/covid19.html, myuw/templates/restclients/customform/upass/index.html, myuw/templates/supporttools/custom_sidebar_links.html, myuw/test/util/test_cache.py, myuw/test/views/test_rest_search.py, myuw/util/cache.py, myuw/views/rest_search.py
https://jira.cac.washington.edu/browse/MUWM-5020
=> clean up attestations related stuff

myuw/static/vue/components/home/international/tacoma.vue, myuw/static/vue/tests/international-stud.test.js
https://jira.cac.washington.edu/browse/MUWM-4933
=> Resolve MUWM-4933

myuw/test/util/test_cache.py, myuw/util/cache.py
https://jira.cac.washington.edu/browse/MUWM-5046
=> Resolve MUWM-5046

myuw/data/resource_link_import.csv
https://jira.cac.washington.edu/browse/MUWM-4871
=> Resolve MUWM-4871

myuw/test/api/test_emaillist.py, myuw/views/api/emaillist.py
https://jira.cac.washington.edu/browse/MUWM-4560
=> Require both instructor and current employee to request a mailing list

docker/prod-values.yml, docker/test-values.yml, docker/vue-values.yml, myuw/management/commands/load_buildings.py, myuw/test/management/commands/test_load_buildings.py
* Add command to update buildings.
* update crons
=> Fff/muwm 3981 (#2676)

Dockerfile
https://jira.cac.washington.edu/browse/MUWM-5050
=> Update django-container to include uwca in the default bundle

myuw/static/vue/components/_common/visual_schedule/course-section.vue
https://jira.cac.washington.edu/browse/MUWM-4938
=> Resolve MUWM-4938

myuw/static/vue/components/home/graduation/pre-application.vue
https://jira.cac.washington.edu/browse/MUWM-5062
=> Add a missing apostrophe

package.json
This PR pins to a working version of Faker.js
=> Pin working version of Faker.js.

myuw/resources/sws/file/student/v5/notice/FE36CCB8F66711D5BE060004AC494F31.json, myuw/test/dao/test_notice.py, myuw/test/dao/test_notice_mapping.py
Add mock AdvOrientRegDateB notice for jnew
=> Add mock AdvOrientRegDateB notice for jnew

myuw_vue/components/home/applicant/tacoma.vue
https://jira.cac.washington.edu/browse/MUWM-5085
=> Resolve MUWM-5085

myuw_vue/components/_templates/tabs/tabs.vue, myuw_vue/mixins/utils.js, myuw_vue/tests/mixins.test.js
Resolve MUWM-5095: all browsers accepts iso8601
=> F/muwm 5095 (#2758)

cypress/fixtures/resources/all.json, cypress/fixtures/resources/pinned.json, myuw/data/category_links_import.csv, myuw/data/resource_link_import.csv, myuw/templates/500.html, myuw_vue/components/_common/grades.vue, myuw_vue/components/home/registration/resources.vue, myuw_vue/tests/mock_data/category_links/academics/javerage.json, myuw_vue/tests/mock_data/resources/all.json, myuw_vue/tests/mock_data/resources/pinned.json
https://jira.cac.washington.edu/browse/MUWM-5097
=> Resolve MUWM-5097

cypress/fixtures/resources/all.json, cypress/fixtures/resources/pinned.json, myuw/data/category_links_import.csv, myuw/data/resource_link_import.csv, myuw/resources/sws/file/student/v5/course/2013_spring_BESS_102/AB.json, myuw/templates/500.html, myuw/templates/admin/notice_edit.html, myuw/test/views/test_notice_admin.py, myuw/views/notice_admin.py, myuw_vue/components/_common/grades.vue, myuw_vue/components/_common/visual_schedule/schedule-tab.vue, myuw_vue/components/home/registration/resources.vue, myuw_vue/tests/mock_data/category_links/academics/javerage.json, myuw_vue/tests/mock_data/resources/all.json, myuw_vue/tests/mock_data/resources/pinned.json, myuw_vue/tests/visual-schedule.test.js
Adding mock data to support changes.  Adding VS warning for overlapping meetings. 
Co-authored-by: Stephen De Vight <devights@uw.edu>
Co-authored-by: William Washington <williamwashington@Williams-MacBook-Pro.local>
=> Fix/muwm 5098 (#2762)

myuw_vue/mixins/utils.js, myuw_vue/tests/mixins.test.js
https://jira.cac.washington.edu/browse/MUWM-3947
=> Resolve MUWM-3947

myuw_vue/components/teaching/course/classlist.vue, myuw_vue/components/teaching/course/final-exam.vue
https://jira.cac.washington.edu/browse/MUWM-5145
=> Resolve MUWM-5145

myuw_vue/components/teaching/course/classlist.vue, myuw_vue/components/teaching/course/final-exam.vue
=> Resolve MUWM-5145 (#2786)

myuw_vue/components/_common/visual_schedule/course-section.vue, myuw_vue/components/teaching/course/classlist.vue, myuw_vue/components/teaching/course/final-exam.vue, myuw_vue/components/teaching/course/grading.vue, myuw_vue/components/teaching/course/materials/website.vue
=> Fix/muwm 5145 (#2788)

myuw_vue/components/home/international/bothell.vue, myuw_vue/components/home/international/seattle.vue, myuw_vue/components/home/international/student.vue, myuw_vue/components/home/international/tacoma.vue, myuw_vue/tests/international-stud.test.js
https://jira.cac.washington.edu/browse/MUWM-5074
https://jira.cac.washington.edu/browse/MUWM-5142
=> Resolving MUWM-5074 and MUWM-5142

myuw/data/resource_link_import.csv
JIRA: https://jira.cac.washington.edu/browse/MUWM-5137
=> Removed old research section

myuw_vue/components/_common/visual_schedule/schedule-tab.vue
https://jira.cac.washington.edu/browse/MUWM-5083
=> Resolve MUWM-5083

myuw/dao/quicklinks.py, myuw/test/dao/test_quicklinks.py, myuw_vue/components/home/quicklinks/covid-links.vue, myuw_vue/components/home/quicklinks/quicklinks.vue, myuw_vue/tests/quicklinks.test.js
https://jira.cac.washington.edu/browse/MUWM-5077
=> Resolve MUWM-5077

myuw_vue/components/profile/help-links.vue, myuw_vue/components/profile/student-profile.vue
Jira: https://jira.cac.washington.edu/browse/MUWM-5149
=> Update profile help links and directory text

myuw_vue/components/home/applicant/applicant.vue, myuw_vue/components/home/applicant/bothell.vue, myuw_vue/components/home/applicant/seattle.vue
https://jira.cac.washington.edu/browse/MUWM-5161
=> Display card for Bothell returning applicant

myuw_vue/components/academics/adviser.vue
https://jira.cac.washington.edu/browse/MUWM-5173
=> resolves MUWM-5173

setup.py
https://jira.cac.washington.edu/browse/MUWM-5189
=> resolve MUWM-5189

myuw_vue/components/_common/course/meeting/location.vue, myuw_vue/components/_common/course/meeting/schedule.vue, myuw_vue/components/teaching/course/course_content.vue
https://jira.cac.washington.edu/browse/MUWM-4552
=> MUWM-4552: add icon display logic

myuw_vue/plugins/logger.js, myuw_vue/plugins/tracklink.js
https://jira.cac.washington.edu/browse/MUWM-5174 pass link_target_url in the linkClick events
=> MUWM-5201: add target_url to linkClick events

myuw/dao/degree.py, myuw/dao/degree_notice.py, myuw/dao/notice_categorization.py, myuw/dao/term.py, myuw/test/api/test_notices.py, myuw/test/dao/test_degree.py, myuw/test/dao/test_degree_notice.py, myuw/test/dao/test_notice_categorization.py, myuw/test/dao/test_term.py, myuw_vue/components/home/graduation/application-submitted.vue, myuw_vue/tests/degree-appl-submitted.test.js, myuw_vue/tests/mock_data/notice/eight.json, myuw_vue/tests/mock_data/notice/javerage.json, myuw_vue/tests/mock_data/notice/javg004.json, myuw_vue/tests/mock_data/profile/eight.json, myuw_vue/tests/mock_data/profile/javerage.json, myuw_vue/tests/mock_data/profile/javg003.json, myuw_vue/tests/mock_data/profile/javg004.json
https://jira.cac.washington.edu/browse/MUWM-5182?jql=project%20%3D%20MUWM%20AND%20fixVersion%20%3D%208.30
=> Fix/muwm 5182 (#2856)

.github/workflows/cicd.yml, myuw_vue/components/_common/course/meeting/schedule.vue
https://jira.cac.washington.edu/browse/MUWM-5207
=> Resolve MUWM-5207

myuw_vue/components/_common/course/course-mode/modality.vue, myuw_vue/components/_common/course/course-mode/mode.vue, myuw_vue/components/home/inst_course_summary/section.vue, myuw_vue/tests/inst-summary.test.js
https://jira.cac.washington.edu/browse/MUWM-5210
=> Hide IN PERSON course mode

myuw_vue/components/academics/adviser.vue
https://jira.cac.washington.edu/browse/MUWM-5200
=> Resolve MUWM-5200: not exclude applicants

myuw/test/api/test_instructor_schedule.py, myuw/test/api/test_instructor_section.py, myuw/test/dao/test_building.py, myuw/test/dao/test_visual_schedule.py, myuw/test/model/test_campus_building.py, setup.py
https://jira.cac.washington.edu/browse/MUWM-5198
=> Resolve MUWM-5198

myuw/templates/profile.html, myuw_vue/components/profile/employee-profile.vue, myuw_vue/components/profile/name-pron.vue, myuw_vue/components/profile/student-profile.vue, myuw_vue/components/profile/user-name.vue, myuw_vue/profile.js
=> MUWM-5134 initial setup of the name-pron card (#2797)

myuw_vue/components/profile/user-name.vue, myuw_vue/tests/user-name.test.js
[MUWM-5134](https://jira.cac.washington.edu/browse/MUWM-5134)
=> MUWM-5134: fix name display

myuw_vue/components/profile/help-links.vue
Jira: https://jira.cac.washington.edu/browse/MUWM-5197
=> Updated broken sidebar link on employee profile page

myuw_vue/components/_common/course/meeting/schedule.vue, myuw_vue/components/home/registration/myplan-courses.vue
[MUWM-2884](https://jira.cac.washington.edu/browse/MUWM-2884)
=> MUWM-2884: reapply csnooke's change

myuw/dao/degree.py, myuw/dao/term.py, myuw/test/dao/test_degree.py, myuw/test/dao/test_term.py, myuw_vue/components/home/graduation/application-submitted.vue, myuw_vue/tests/degree-appl-submitted.test.js, myuw_vue/tests/mock_data/profile/javerage.json
[Jira](https://jira.cac.washington.edu/browse/MUWM-5232)
=> Qa to Main  fix/MUWM-5232

myuw_vue/components/academics/grad-status.vue
https://jira.cac.washington.edu/browse/MUWM-5236
=> Resolve MUWM-5236

myuw/templates/accounts.html
[MUWM-5245](https://jira.cac.washington.edu/browse/MUWM-5245)
=> Resolve MUWM-5245

myuw_vue/components/teaching/teaching-resources.vue
https://jira.cac.washington.edu/browse/MUWM-5240
=> Removed broken FROG link, added new grading resources links

myuw/resources/sws/file/student/v5/enrollment.json_reg_id_9136CCB8F66711D5BE060004AC494005_verbose_true_transcriptable_course_all_changed_since_date_, myuw_vue/components/home/major-declaration/declare-major.vue, myuw_vue/mixins/utils.js, myuw_vue/tests/declare-major.test.js, myuw_vue/tests/mixins.test.js, myuw_vue/tests/mock_data/profile/javgPremajor.json
https://jira.cac.washington.edu/browse/MUWM-5261
=> resolve MUWM-5261

myuw_vue/components/home/new_student/to-register.vue
[MUWM-5269](https://jira.cac.washington.edu/browse/MUWM-5269)
=> removing covid immunization hard-coded notice.

docker/prod-values.yml, myuw/dao/category_notice.py, myuw/dao/myuw_notice.py, myuw/dao/notice_categorization.py, myuw/templates/admin/notice_list.html, myuw/test/api/test_notices.py, myuw/test/dao/test_category_notice.py, myuw/test/dao/test_myuw_notice.py, myuw/test/dao/test_notice_categorization.py, myuw_vue/components/home/graduation/application-submitted.vue, myuw_vue/tests/degree-appl-submitted.test.js, myuw_vue/tests/mock_data/notice/eight.json, myuw_vue/tests/mock_data/notice/javerage.json, myuw_vue/tests/mock_data/notice/javg004.json, setup.py
[MUWM-5263](https://jira.cac.washington.edu/browse/MUWM-5263)
reset minReplicas
=> Feature/muwm 5263 (#2954)

myuw_vue/components/_templates/boilerplate/boilerplate.vue
https://jira.cac.washington.edu/browse/MUWM-5276
=> Resolve MUWM-5276. Clean up extra space in link

myuw/test/util/test_cache.py, myuw/util/cache.py
https://jira.cac.washington.edu/browse/MUWM-5275
=> Resolve MUWM-5275

myuw/dao/myuw_notice.py, myuw/dao/term.py, myuw/templates/admin/notice_edit.html, myuw/test/dao/test_myuw_notice.py, myuw/test/dao/test_term.py
[MUWM-5273](https://jira.cac.washington.edu/browse/MUWM-5273):  fix the bug in [#2949](https://github.com/uw-it-aca/myuw/pull/2949)
=> Fix bug in get_first_day_quarter

.github/workflows/cicd.yml, myuw_vue/components/home/graduation/pre-application.vue, myuw_vue/mixins/utils.js, myuw_vue/tests/degree-pre-appl.test.js, myuw_vue/tests/mixins.test.js, myuw_vue/tests/mock_data/profile/javg001-nomajor.json
https://jira.cac.washington.edu/browse/MUWM-5278
=> Resolve MUWM-5278

.github/workflows/cicd.yml, myuw/management/commands/load_buildings.py, myuw/models/campus_building.py, myuw/test/management/commands/test_load_buildings.py, setup.py
Automatically clean up duplicates
=> Clean up dupplicate entries

docker/prod-values.yml, docker/test-values.yml, docker/vue-values.yml, myuw/management/commands/db_cleanup.py, myuw/test/management/commands/test_db_cleanup.py
Change to ongoing clehttps://jira.cac.washington.edu/browse/MUWM-5284?jql=project%20%3D%20MUWM%20AND%20fixVersion%20%3D%208.52an up
=> F/muwm 5284 (#2979)

myuw/management/commands/db_cleanup.py, myuw_vue/components/home/new_student/to-register.vue
MUWM-5286: https://jira.cac.washington.edu/browse/MUWM-5286
=> Update immunizations deadline text and link for all three campuses

myuw_vue/components/teaching/classlist/class-student-list.vue
Jira: https://jira.cac.washington.edu/browse/MUWM-5281
=> Add pronoun guidance alert

myuw_vue/components/profile/student-profile.vue
MUWM-5290: https://jira.cac.washington.edu/browse/MUWM-5290
=> Comment out residency status

.github/workflows/cicd.yml, myuw_vue/components/home/major-declaration/declare-major.vue, myuw_vue/tests/declare-major.test.js
https://jira.cac.washington.edu/browse/MUWM-5288
=> Resolved MUWM-5288

myuw/data/resource_link_import.csv
Jira: https://jira.cac.washington.edu/browse/MUWM-4257
=> Add ASTRA link to UW resources

docker/prod-values.yml, myuw/management/commands/db_cleanup.py
Apply MyUW term switch, reduce data in the two largest tables
=> Fix/term switch (#3039)

.github/workflows/cicd.yml, Dockerfile, docker/dev-values.yml, docker/prod-values.yml, docker/test-values.yml, docker/vue-values.yml, myuw/management/commands/db_cleanup.py
[MUWM-5196](https://jira.cac.washington.edu/browse/MUWM-5196)
=> Resolve MUWM-5196: switch over to postgres DB

Dockerfile, docker/dev-values.yml, docker/prod-values.yml, docker/test-values.yml, docker/vue-values.yml, myuw/management/commands/db_cleanup.py
Resolve MUWM-5196: switch over to postgres DB
=> Resolve MUWM-5196: switch over to postgres DB (#3034)

myuw_vue/components/_common/course/textbook.vue, myuw_vue/mixins/courses.js
https://jira.cac.washington.edu/browse/MUWM-5326
=> Resolve MUWM-5326

myuw_vue/components/_common/course/inst/linked-section.vue, myuw_vue/components/teaching/course/course_content.vue, myuw_vue/mixins/courses.js, myuw_vue/vuex/store/schedule/instructor.js
https://jira.cac.washington.edu/browse/MUWM-5320?jql=project%20%3D%20MUWM%20AND%20fixVersion%20%3D%209.4
=> Fix/muwm 5320 (#3058)

.github/workflows/cicd.yml, docker/settings.py, myuw/test/api/test_iasystem.py, myuw/test/dao/test_iasystem.py, myuw/test/dao/test_notice_mapping.py, myuw/test/views/lti/__init__.py, myuw/test/views/test_page.py, myuw/views/display_dates.py, setup.py
[MUWM-5310](https://jira.cac.washington.edu/browse/MUWM-5310)
=> Resolve MUWM-5310

myuw_vue/components/home/international/new-student.vue, myuw_vue/components/home/new_student/critical-info.vue, myuw_vue/components/home/new_student/summer-efs.vue, myuw_vue/components/home/new_student/to-register.vue, myuw_vue/tests/to-register.test.js
MUWM-5056 NSC content updates
https://jira.cac.washington.edu/browse/MUWM-5256?jql=project%20%3D%20MUWM%20AND%20fixVersion%20%3D%209.7
=> NSC content updates (#3073)

docker/dev-values.yml, docker/prod-values.yml, docker/test-values.yml, docker/vue-values.yml
clean up values no longer used
=> Clean/image (#3077)

docker/prod-values.yml, myuw_vue/components/home/major-declaration/declare-major.vue, myuw_vue/components/home/major-declaration/major-bot.vue, myuw_vue/components/home/major-declaration/major-sea.vue, myuw_vue/components/home/major-declaration/major-tac.vue, myuw_vue/tests/declare-major.test.js
=> MUWM-5297: enable campus specific major info (#3074)

Dockerfile.cypress
https://jira.cac.washington.edu/browse/MUWM-5340
=> cypress to use latest node

myuw/data/category_links_import.csv, myuw_vue/components/_common/hr-payroll.vue
https://jira.cac.washington.edu/browse/MUWM-5341
=> Resolve MUWM-5341

myuw/data/resource_link_import.csv, myuw_vue/components/home/major-declaration/declare-major.vue, myuw_vue/components/home/major-declaration/major-bot.vue, myuw_vue/tests/declare-major.test.js
MUWM-5296, 
---------
Co-authored-by: Fang Lin <fanglin@uw.edu>
=> Fix/muwm 5296 (#3114)

myuw/data/resource_link_import.csv, myuw_vue/components/home/major-declaration/declare-major.vue, myuw_vue/components/home/major-declaration/major-bot.vue, myuw_vue/tests/declare-major.test.js
https://jira.cac.washington.edu/browse/MUWM-5339?jql=project%20%3D%20MUWM%20AND%20fixVersion%20%3D%209.13
=> Release 9.13

.github/workflows/cicd.yml, myuw/dao/student_profile.py, myuw_vue/components/home/major-declaration/declare-major.vue
https://jira.cac.washington.edu/browse/MUWM-5345
=> Resolve MUWM-5345

package.json
=> Removes unused package. Breaks ARM based mac builds.

myuw_vue/components/_templates/card-status.vue, myuw_vue/components/accounts/tuition-fees.vue, myuw_vue/components/textbooks/textbooks.vue
https://jira.cac.washington.edu/browse/MUWM-5354?jql=project%20%3D%20MUWM%20AND%20fixVersion%20%3D%209.19
=> Feature/muwm 5351 a11y (#3142)

.github/workflows/cicd.yml, docker/prod-values.yml, myuw/resources/pws/file/identity/v2/person.json_student_number_1033334_verbose_on, myuw/templates/restclients/customform/sws/student.html, myuw/test/views/test_rest_search.py, myuw/views/rest_search.py, myuw_vue/components/home/new_student/to-register.vue, package.json
Resolve MUWM-5355 (William)
Update git actions, adjust minReplicas based on weekend load, support student number on search  ---------
=> revising static notices messaging & styles (#3147)

docker/prod-values.yml, myuw/dao/canvas.py, myuw/templates/restclients/customform/canvas/active_enrollments.html, myuw/templates/supporttools/custom_sidebar_links.html, myuw/test/dao/test_canvas.py, myuw/views/rest_search.py
https://jira.cac.washington.edu/browse/MUWM-5362?jql=project%20%3D%20MUWM%20AND%20fixVersion%20%3D%209.21
Resolve MUWM-5362. Up maxReplicas 150
=> Fix/muwm 5362 (#3152)

myuw/test/util/test_cache.py, myuw/util/cache.py, myuw/views/rest_search.py, myuw_vue/components/home/summaries.vue, myuw_vue/tests/summaries.test.js
Resolve MUWM-5364.  Restrict loading of hfs and lib data.  Change 5xx error cache policy to 7 min
=> Resolve MUWM-5364 (#3161)

myuw/data/resource_link_import.csv
https://jira.cac.washington.edu/browse/MUWM-5380
=> Resolve MUWM-5380

Dockerfile
Address the SSLCertVerificationError
=> points to the latest django-container

.github/workflows/cicd.yml, myuw_vue/components/academics/adviser.vue
https://jira.cac.washington.edu/browse/MUWM-5390
=> Resolve MUWM-5390

.github/workflows/cicd.yml, myuw/test/api/test_instructor_schedule.py, myuw/views/api/instructor_schedule.py
https://jira.cac.washington.edu/browse/MUWM-5392
=> Resolve MUWM-5392

docker/prod-values.yml, myuw/dao/applications.py, myuw/resources/gws/file/group_sws/v3/search_member_jerror_scope_all_type_direct_stem_uw_affiliation_name_, myuw/test/api/test_applications.py, myuw_vue/components/home/applicant/applicant.vue, myuw_vue/tests/applicant.test.js
https://jira.cac.washington.edu/browse/MUWM-5391?jql=project%20%3D%20MUWM%20AND%20fixVersion%20%3D%209.34
=> F/muwm 5391 (#3198)

docker/prod-values.yml, myuw/templates/_common/direct-links.html, myuw_vue/components/home/applicant/applicant.vue
https://jira.cac.washington.edu/browse/MUWM-5397
=> Resolve MUWM-5397

docker/prod-values.yml, myuw/templates/_common/direct-links.html, myuw_vue/components/home/applicant/applicant.vue
=> Resolve MUWM-5397 (#3212)

myuw/data/category_links_import.csv, myuw/data/resource_link_import.csv, myuw/views/api/instructor_schedule.py
=> Resolve MUWM-5402 (#3224)

.github/workflows/cicd.yml, myuw/resources/coda/file/api/v1/course/2013-spring-ESS-102-A/majors/1, myuw/resources/coda/file/api/v1/course/2013-spring-PHYS-121-A/majors/1, myuw/resources/coda/file/api/v1/course/2013-spring-PHYS-121-AC/majors/1, myuw/resources/coda/file/api/v1/course/2013-spring-PHYS-121-AQ/majors/1, myuw/resources/coda/file/api/v1/course/2013-spring-TRAIN-100-A/majors/1, myuw/test/api/test_instructor_section.py, myuw_vue/components/teaching/classlist/statistics.vue, myuw_vue/tests/mock_data/classlist/2013-spring-ESS-102-A.json
https://jira.cac.washington.edu/browse/MUWM-5228
=> Resolve MUWM-5228

.github/workflows/cicd.yml, myuw/data/resource_link_import.csv, myuw_vue/components/teaching/teaching-resources.vue, myuw_vue/components/textbooks/section.vue, myuw_vue/components/textbooks/textbooks.vue, myuw_vue/tests/textbooks.test.js
[MUWM-5413](https://jira.cac.washington.edu/browse/MUWM-5413)
=> resolve MUWM-5413

myuw_vue/components/home/former_student/continuing-education.vue, myuw_vue/tests/continuing-education.test.js
https://jira.cac.washington.edu/browse/MUWM-5412
=> Resolve MUWM-5412

myuw/dao/quicklinks.py, myuw/test/api/test_quicklinks.py, myuw/test/dao/test_quicklinks.py, myuw/views/api/link.py, myuw_vue/components/home/quicklinks/quicklinks.vue
https://jira.cac.washington.edu/browse/MUWM-5416
=> Merge popular links into default links (quicklinks.csv)

myuw_vue/components/home/former_student/continuing-education.vue, myuw_vue/tests/continuing-education.test.js
=> Resolve MUWM-5412 (#3246)

myuw_vue/components/home/registration/resources.vue
https://jira.cac.washington.edu/browse/MUWM-5401
=> Resolve MUWM-5401

myuw_vue/components/home/registration/resources.vue
=> Resolve MUWM-5401 (#3254)

myuw_vue/components/home/new_student/to-register.vue
[MUWM-5419](https://jira.cac.washington.edu/browse/MUWM-5419)[MUWM-5419](https://jira.cac.washington.edu/browse/MUWM-5419)
=> Resolve MUWM-5419

.github/workflows/cicd.yml, myuw/views/api/emaillist.py
https://jira.cac.washington.edu/browse/MUWM-5430
=> Resolve MUWM-5430

myuw/views/api/emaillist.py
=> Resolve MUWM-5430 (#3285)
